name: challenge
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  http: ^1.2.2
  go_router: ^14.2.7
  dartz: ^0.10.1
  meta: ^1.15.0
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.2.1
  provider: ^6.1.2

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
